import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#faf8ef',
  },
  containerShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  topSection: {
    paddingHorizontal: 16,
  },
  middleSection: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 200,
    paddingHorizontal: 16,
  },
  bottomSection: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#faf8ef',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#776e65',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(143, 122, 102, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarEmoji: {
    fontSize: 24,
  },
  headerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  modeLabel: {
    fontSize: 12,
    opacity: 0.7,
  },
  headerRight: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconText: {
    fontSize: 18,
  },
  scoreContainer: {
    flexDirection: 'row',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
  },
  scoreItem: {
    flex: 1,
    alignItems: 'center',
  },
  scoreDivider: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
  },
  scoreLabel: {
    fontSize: 12,
    marginBottom: 4,
  },
  scoreValue: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  boardContainer: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    padding: 10,
    marginBottom: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  modeSelectionContainer: {
    width: '100%',
    height: 390,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#bbada0',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  modeSelectionBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 11,
  },
  modeSelectionContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  pauseOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(250, 248, 239, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  pauseEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  pauseText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 8,
  },
  pauseSubtext: {
    fontSize: 14,
    color: '#776e65',
  },
  modeSelection: {
    width: '100%',
    height: 390,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 16,
    marginBottom: 16,
    borderWidth: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  modeSelectionTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  modeSelectionSubtitle: {
    fontSize: 14,
    opacity: 0.7,
    marginBottom: 32,
    textAlign: 'center',
  },
  modeSection: {
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
    marginBottom: 32,
  },
  modeSectionBorder: {
    borderTopWidth: 2,
    paddingTop: 24,
  },
  modeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  sizeButtons: {
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'center',
  },
  sizeButton: {
    width: 80,
    height: 52,
    borderRadius: 10,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizeButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#776e65',
  },
  actionButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  actionButton: {
    flex: 1,
    minWidth: '45%',
    height: 52,
    borderRadius: 10,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  actionButtonDisabled: {
    opacity: 0.4,
    backgroundColor: '#ccc0b3',
  },
  actionButtonTextDisabled: {
    color: '#aaa090',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  playerInfoModalContent: {
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#776e65',
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalCloseButton: {
    padding: 8,
    marginLeft: 8,
  },
  modalCloseButtonText: {
    fontSize: 24,
    color: '#776e65',
    fontWeight: 'bold',
  },
  modalMessage: {
    fontSize: 16,
    color: '#776e65',
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: '#8f7a66',
    borderWidth: 1,
  },
  modalButtonSecondary: {
    borderWidth: 1,
    borderColor: '#8f7a66',
  },
  modalButtonDanger: {
    backgroundColor: '#dc3545',
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  modalButtonSecondaryText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#8f7a66',
  },
  playerInfoContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  playerInfoEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  playerInfoNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  playerInfoName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#776e65',
    marginRight: 8,
  },
  playerInfoDeleteButton: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: '#fee2e2',
  },
  playerInfoDeleteButtonText: {
    fontSize: 16,
  },
  playerInfoZodiac: {
    fontSize: 16,
    color: '#776e65',
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#bbada0',
  },
  settingInfo: {
    flex: 1,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 4,
  },
  settingDescription: {
    fontSize: 12,
    color: '#776e65',
    opacity: 0.7,
  },
  settingSection: {
    marginTop: 16,
    paddingTop: 8,
  },
  settingSectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 8,
  },
  dataManagementButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  dataButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 2,
    backgroundColor: '#f5f5f4',
    alignItems: 'center',
  },
  dataButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#776e65',
  },
  settingToggle: {
    width: 60,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  settingToggleActive: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  settingToggleText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#6b7280',
  },
  dangerButton: {
    backgroundColor: '#fef2f2',
    borderWidth: 1.5,
    borderColor: '#fca5a5',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: '#dc2626',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  dangerButtonText: {
    color: '#dc2626',
    fontSize: 15,
    fontWeight: '600',
  },
  opacitySliderWrapper: {
    flex: 1,
    marginLeft: 16,
  },
  opacitySliderTrack: {
    width: '100%',
    height: 32,
    position: 'relative',
    justifyContent: 'center',
  },
  opacitySliderFill: {
    height: 6,
    borderRadius: 3,
    position: 'absolute',
    top: 13,
  },
  opacitySliderThumb: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    top: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    marginLeft: -16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  thumbInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  opacityMarkers: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  opacityMarkerText: {
    fontSize: 12,
    minWidth: 60,
    alignItems: 'center',
  },
  opacityValueText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#776e65',
  },
  settingButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  seasonButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    backgroundColor: '#f3f4f6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  seasonButtonActive: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  seasonButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6b7280',
  },
  seasonButtonTextActive: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  userListLoading: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  userListLoadingText: {
    marginTop: 12,
    fontSize: 16,
  },
  userListEmpty: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  userListEmptyText: {
    fontSize: 16,
    textAlign: 'center',
    paddingVertical: 20,
  },
  userItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 6,
    borderWidth: 1,
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  userAvatarEmoji: {
    fontSize: 18,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  userZodiac: {
    fontSize: 12,
    opacity: 0.7,
  },
  userListScroll: {
    maxHeight: 300,
  },
  confirmDialogContent: {
    paddingVertical: 16,
    paddingHorizontal: 8,
  },
  confirmDialogMessage: {
    fontSize: 16,
    color: '#776e65',
    textAlign: 'center',
    marginBottom: 12,
  },
  confirmDialogWarning: {
    fontSize: 14,
    color: '#dc3545',
    textAlign: 'center',
  },
  historyFilterContainer: {
    flexDirection: 'column',
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  historyFilterButtonSmall: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#e7e5e4',
    borderWidth: 1,
    borderColor: '#d6d3d1',
    minWidth: 70,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyFilterButtonActive: {
    backgroundColor: '#8f7a66',
    borderColor: '#8f7a66',
  },
  historyFilterButtonActiveEasy: {
    backgroundColor: '#90ee90',
    borderColor: '#90ee90',
  },
  historyFilterButtonActiveHard: {
    backgroundColor: '#ef9a9a',
    borderColor: '#ef9a9a',
  },
  historyFilterButtonTextSmall: {
    fontSize: 11,
    color: '#78716c',
    fontWeight: '600',
  },
  historyFilterButtonTextActive: {
    color: '#ffffff',
  },
  historyLoadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  historyLoadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#78716c',
  },
  historyEmptyContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  historyEmptyText: {
    fontSize: 16,
    color: '#78716c',
  },
  historyDebugText: {
    fontSize: 12,
    color: '#dc2626',
    marginTop: 8,
    textAlign: 'center',
  },
  historyScroll: {
    flex: 1,
  },
  historyScrollContent: {
    paddingBottom: 16,
  },
  historyItem: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
  },
  historyItemAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f2b179',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  historyItemAvatarEmoji: {
    fontSize: 20,
  },
  historyItemLeft: {
    flex: 1,
  },
  historyItemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#776e65',
  },
  historyItemMode: {
    fontSize: 12,
    color: '#776e65',
    opacity: 0.7,
    marginTop: 2,
  },
  historyItemRight: {
    alignItems: 'flex-end',
  },
  historyItemScore: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#d97706',
  },
  historyItemTime: {
    fontSize: 12,
    color: '#78716c',
    marginTop: 2,
  },
  gameResultModalContent: {
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  gameResultHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  gameResultEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  gameResultTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#776e65',
    textAlign: 'center',
  },
  gameResultAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#f2b179',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  gameResultAvatarEmoji: {
    fontSize: 32,
  },
  gameResultInfo: {
    alignItems: 'center',
    marginBottom: 24,
  },
  gameResultPlayerName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 20,
  },
  confirmMessageContainer: {
    marginBottom: 20,
  },
  confirmMessage: {
    fontSize: 18,
    textAlign: 'center',
    lineHeight: 24,
  },
  gameResultStats: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
  },
  gameResultStat: {
    alignItems: 'center',
    flex: 1,
  },
  gameResultStatBorder: {
    borderRightWidth: 1,
  },
  gameResultStatLabel: {
    fontSize: 12,
    color: '#776e65',
    opacity: 0.7,
    marginBottom: 4,
  },
  gameResultStatValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#d97706',
  },
  historyModalContent: {
    width: '100%',
    maxWidth: 400,
    height: '80%',
    flexDirection: 'column',
  },
  historyListContainer: {
    flex: 1,
  },
  historyFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  historyFilterLabel: {
    fontSize: 15,
    fontWeight: '600',
    width: 50,
    marginRight: 12,
  },
  historyFilterButtons: {
    flexDirection: 'row',
    gap: 8,
    flex: 1,
  },
  historyFilterButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#e7e5e4',
    borderWidth: 1,
    borderColor: '#d6d3d1',
    minWidth: 70,
    alignItems: 'center',
  },
  historyFilterButtonText: {
    fontSize: 12,
    color: '#78716c',
    fontWeight: '600',
  },
  debugPanelOverlay: {
    position: 'absolute',
    top: undefined,
    left: 16,
    right: 16,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  debugPanel: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    height: 'auto',
  },
  debugPanelTitle: {
    fontSize: 12,
    marginBottom: 12,
  },
  debugButtonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  debugTileButton: {
    width: 60,
    height: 44,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#bbada0',
  },
  debugTileButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
});
